In [1]:
# cloud computing paper: training and testing of DDoS attack detector
import random
import numpy as np
import pandas as pd

import keras as kr
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, TimeDistributed

Using TensorFlow backend.


In [2]:
#training data
intervals = (1, 0.5, 0.1, 0.01, 0.005, 0.001)
no_att_int = (1, 0.5, 0.1, 0.01)

ddos_train = []
for _ in range(4):
    with_atk = random.choices(intervals, k=1000)
    #without_atk = random.choices(intervals, k=300)
    #with_atk.extend(without_atk)
    ddos_train.append(with_atk)
 
tr = pd.DataFrame(ddos_train)
train_df = pd.DataFrame(tr.T.values, columns = ("VM1", "VM2", "VM3", "VM4"))
print(train_df.shape)

(1000, 4)


In [3]:
target = [0] * train_df.shape[0]
vals = train_df.values 

for i in range(train_df.shape[0]):
    if any(vals[i] == 0.001):
        target[i] = 1

print(target[:10])
train_df.head(10)

[1, 1, 1, 1, 1, 1, 0, 1, 0, 1]


VM1    VM2    VM3    VM4
0  0.001  0.005  0.001  0.100
1  0.001  0.005  1.000  0.005
2  0.001  1.000  0.001  0.001
3  0.010  0.500  0.001  1.000
4  0.010  0.010  0.500  0.001
5  0.500  0.100  0.001  1.000
6  0.005  0.100  0.005  0.005
7  0.500  0.001  0.500  1.000
8  0.100  1.000  0.005  0.010
9  0.100  0.001  0.010  0.010

In [4]:
X = train_df.values
Y = target

model = Sequential()
model.add(Dense(5, input_dim=4, activation='tanh'))
model.add(Dense(1, activation='tanh'))

model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
history = model.fit(X, Y, epochs=100, batch_size=10)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
1000/1000 [==============================] - 1s 1ms/step - loss: 0.3972 - acc: 0.4790
Epoch 2/100
1000/1000 [==============================] - 0s 65us/step - loss: 0.3043 - acc: 0.4380
Epoch 3/100
1000/1000 [==============================] - 0s 56us/step - loss: 0.2794 - acc: 0.3990
Epoch 4/100
1000/1000 [==============================] - 0s 54us/step - loss: 0.2671 - acc: 0.3760
Epoch 5/100
1000/1000 [==============================] - 0s 50us/step - loss: 0.2576 - acc: 0.3750
Epoch 6/100
1000/1000 [==============================] - 0s 49us/step - loss: 0.2499 - acc: 0.4780
Epoch 7/100
1000/1000 [==============================] - 0s 47us/step - loss: 0.2435 - acc: 0.6100
Epoch 8/100
1000/1000 [==============================] - 0s 46us/step - loss: 0.2388 - acc: 0.6120
Epoch 9/100
1000/1000 [==============================] - 0s 59us/step - loss: 0.2352 - ac

In [5]:
loss, accuracy = model.evaluate(X, Y)
print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))

1000/1000 [==============================] - 0s 24us/step

Loss: 0.22, Accuracy: 64.00%


In [6]:
x_train = train_df.values.reshape(1000,1,4)
y_train = pd.DataFrame(target).values.reshape(1000, 1,1)

print(x_train[:10], y_train[:10], sep="\n")
model=Sequential()
model.add(SimpleRNN(input_dim=4, output_dim=5, return_sequences = True))
model.add(TimeDistributed(Dense(output_dim = 1, activation  =  "relu")))
model.compile(loss = "mse", optimizer = "adam", metrics=["accuracy"])
model.fit(x_train, y_train, nb_epoch = 200, batch_size = 32)

[[[0.001 0.005 0.001 0.1  ]]

 [[0.001 0.005 1.    0.005]]

 [[0.001 1.    0.001 0.001]]

 [[0.01  0.5   0.001 1.   ]]

 [[0.01  0.01  0.5   0.001]]

 [[0.5   0.1   0.001 1.   ]]

 [[0.005 0.1   0.005 0.005]]

 [[0.5   0.001 0.5   1.   ]]

 [[0.1   1.    0.005 0.01 ]]

 [[0.1   0.001 0.01  0.01 ]]]
[[[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[0]]

 [[1]]

 [[0]]

 [[1]]]


/home/amogh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  
/home/amogh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `SimpleRNN` call to the Keras 2 API: `SimpleRNN(return_sequences=True, input_shape=(None, 4), units=5)`
  
/home/amogh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1)`
  import sys
/home/amogh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  if __name__ == '__main__':


Epoch 1/200
1000/1000 [==============================] - 1s 636us/step - loss: 0.4274 - acc: 0.4590
Epoch 2/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.3986 - acc: 0.4510
Epoch 3/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.3597 - acc: 0.4480
Epoch 4/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.3256 - acc: 0.4360
Epoch 5/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.2995 - acc: 0.4390
Epoch 6/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.2834 - acc: 0.4340
Epoch 7/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.2721 - acc: 0.4280
Epoch 8/200
1000/1000 [==============================] - 0s 33us/step - loss: 0.2636 - acc: 0.4130
Epoch 9/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.2571 - acc: 0.4370
Epoch 10/200
1000/1000 [==============================] - 0s 30us/step - loss: 0.2518 - acc: 0.5200
Epoch 11

1000/1000 [==============================] - 0s 40us/step - loss: 0.2289 - acc: 0.6100
Epoch 84/200
1000/1000 [==============================] - 0s 34us/step - loss: 0.2289 - acc: 0.6120
Epoch 85/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.2288 - acc: 0.6080
Epoch 86/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.2290 - acc: 0.6140
Epoch 87/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.2288 - acc: 0.6090
Epoch 88/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.2289 - acc: 0.6130
Epoch 89/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.2295 - acc: 0.6030
Epoch 90/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.2288 - acc: 0.6120
Epoch 91/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.2288 - acc: 0.6110
Epoch 92/200
1000/1000 [==============================] - 0s 34us/step - loss: 0.2288 - acc: 0.6050
Epoch 93/200


In [7]:
from sklearn import linear_model

clf = linear_model.LogisticRegression(C=1e2)
clf.fit(X, Y)

/home/amogh/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
probabilities = clf.predict(X)
predictions = [float(x) for x in probabilities]
accuracy = np.mean([1-abs(predictions[i] - Y[i]) for i in range(len(predictions))])
print("Prediction Accuracy: %.2f%%" % (accuracy*100))
print(target[:10])
clf.predict(X)[:10]

Prediction Accuracy: 62.20%
[1, 1, 1, 1, 1, 1, 0, 1, 0, 1]


array([1, 1, 1, 0, 1, 0, 1, 0, 1, 1])